nimbus.seeds: [node103.ib.cluster]

storm.zookeeper.port: 2186
storm.zookeeper.servers: [node103.ib.cluster]

supervisor.slots.ports: [13000]
supervisor.supervisors: [node106.ib.cluster,node107.ib.cluster,node108.ib.cluster,node109.ib.cluster]

storm.local.dir: "/local/ddps2016/storm-local"
storm.log.dir: "/local/ddps2016/storm-logs" 

worker.childopts: "-Xmx16G"

