nimbus.seeds: [node102.ib.cluster]

storm.zookeeper.port: 2186
storm.zookeeper.servers: [node102.ib.cluster]

supervisor.slots.ports: [13000]
supervisor.supervisors: [node105.ib.cluster,node106.ib.cluster]

storm.local.dir: "/local/ddps2016/storm-local"
storm.log.dir: "/local/ddps2016/storm-logs" 

worker.childopts: "-Xmx16G"

